### ISSUE TITLE
Make `slaunch_module` reentrant

### ISSUE THREAD

**Issue by krystian-hebel** [TrenchBoot/grub#11]
Currently, `slaunch_module` doesn't handle multiple invocations very well. On subsequent calls, it overwrites pointer to previous SINIT without freeing it, leaking memory in the process. On boot only last module is used, given that it matches the platform.

Ideally, this function should fall back to previously loaded module if new one doesn't match the platform or is in older version; otherwise it should properly free memory used by previous module.

This would allow scripts in `grub.d` to iterate over SINITs in `/boot` and create `slaunch_module` entry for each one, removing from user the burden of manually copying just the proper SINIT.

**Comment by SergiiDmytruk** [comment]
Closed by 13bf69f550024b02fb94fa4073c84643f4d91574, but GitHub decided to not do it.
